name: fetch-secrets
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  CONJUR_URL: https://aruntenant.secretsmgr.cyberark.cloud
  CONJUR_ACCOUNT: conjur
  CONJUR_AUTHN_ID: github
  SECRET_ID: data/vault/StarAi-Dev/Arun-Staridb/username

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Import secrets from Conjur
        uses: cyberark/conjur-action@v2.0.12
        with:
          url:      ${{ env.CONJUR_URL }}
          account:  ${{ env.CONJUR_ACCOUNT }}
          authn_id: ${{ env.CONJUR_AUTHN_ID }}
          # Map Conjur IDs -> env vars used later in the job
          secrets: |
            ${{ env.SECRET_ID }}|DB_USERNAME
            # data/vault/StarAi-Dev/Arun-Staridb/password|DB_PASSWORD   # <- add more if needed

      - name: Use secret (example; don't print it)
        run: |
          echo "DB_USERNAME length: ${#DB_USERNAME}"
          # e.g., pass to your app:
          # ./deploy --db-user "$DB_USERNAME"
